version: '3.7'
services:  
  arcane-agent-host:  
    image: ghcr.io/getarcaneapp/arcane-headless:latest
    container_name: arcane-agent-host-umbrel
    restart: unless-stopped
    stop_grace_period: 1m
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - arcane-data:/app/data
    environment:
      - AGENT_MODE=true
      - AGENT_TOKEN=${ARCANE_AGENT_TOKEN}
      - MANAGER_API_URL=http://${DEVICE_DOMAIN_NAME}:3552
    ports:
      - "3553:3553"
    
volumes:
      arcane-data: