version: "3.7"
services:
  arcane-agent-host-umbrel:
    image: ghcr.io/getarcaneapp/arcane-headless:v1.15
    container_name: arcane-agent-host-umbrel
    restart: unless-stopped
    networks:
      - umbrel_main_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA_DIR}/data:/app/data    
    environment:
      - AGENT_MODE=true
      - AGENT_TOKEN=${ARCANE_AGENT_TOKEN}
      - MANAGER_API_URL=http://${DEVICE_HOSTNAME}:3552
    env_file:
      - ${APP_DATA_DIR}/settings.env
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"

volumes:
  arcane-data:

networks:
  umbrel_main_network:
    external: true