services:
  viseron:
    image: roflcoopter/viseron:latest
    container_name: viseron
    restart: unless-stopped
    shm_size: "1024mb"
    privileged: true
    ports:
      - 8888:8888
    volumes:
      - ${APP_DATA_DIR}/segments:/segments
      - ${APP_DATA_DIR}/snapshots:/snapshots
      - ${APP_DATA_DIR}/thumbnails:/thumbnails
      - ${APP_DATA_DIR}/event_clips:/event_clips
      - ${APP_DATA_DIR}/timelapse:/timelapse
      - ${APP_DATA_DIR}/config:/config
      - /etc/localtime:/etc/localtime:ro