ffmpeg:
  camera:
    camera_one:
      name: camera_one
      host: 192.168.0.x
      port: 554
      path: /channel=0_stream=0&onvif=0.sdp
      username: username
      password: password     
      substream:
        port: 554
        path: /user=username_password=password_channel=0_stream=1&onvif=0.sdp

    camera_two:
      name: camera_two
      host: 192.168.0.x
      port: 554
      path: /channel=0_stream=0&onvif=0.sdp
      username: username
      password: password
      substream:
        port: 554
        path: /user=username_password=password_channel=0_stream=1&onvif=0.sdp
nvr:
  camera_one:
  camera_two:

mog2:
  motion_detector:
    cameras:
      camera_one:
        detect_shadows: true
        fps: 1      
        trigger_event_recording: true
      camera_two:
        detect_shadows: true
        fps: 1
        trigger_event_recording: true

logger:
  logs:
    viseron.components.ptz: debug
    viseron.components.storage: debug
    viseron.components.nvr: debug
    viseron.components.ffmpeg: debug

storage:
  recorder:
    tiers:
      - path: /segments # Will store segments in /segments folder inside the container
        events:
          max_size:
            gb: 20
          max_age:
            days: 7